Bugfix map_mods for negative chemical compositions
ursgal/ursgal pull request #194
Opened 2021-09-08 15:57 UTC by StSchulze

When defining a non-unimod modification, chemical compositions can contain negative values.
Using `use` instead of `add_chemical_composition` should solve the issue

2021-10-15 13:57 UTC, StSchulze commented
After switching to Python >= 3.7, this should be good to go

2021-10-18 08:34 UTC, MKoesters requested changes

2021-10-18 08:34 UTC, MKoesters commented on tests/map_mods_test.py
> +        os.remove(usermods_file)
Why `file_exists`?
Its set to `True`, if `os.path.exists(usermods_file)`

Later, you check 

```
if file_exists:
        shutil.copy(tmp_usermods_file, usermods_file)
        os.remove(tmp_usermods_file)
    elif os.path.exists(usermods_file):
        os.remove(usermods_file)
```

So the second condition can never kick in, because either the first is True and executed or the second is `False`, or don't I understand something?

2021-10-18 14:04 UTC, StSchulze commented on tests/map_mods_test.py
> +        os.remove(usermods_file)
The first part (81-86) checks if a userdefined mod file exists. If it does, it should not be deleted or altered by the tests, because we don't want to mess with the files of users. So yes, 96-97 will never kick in if the file exists, which is what is desired.

The second part (93-97) checks whether a new file has been created by the tests (which should be the case due to the new test cases) and deletes it. But only if it's a file that didn't exist before, otherwise it's using the original file, which was stored as an unaltered tmp copy, and removes the altered version.

2021-10-29 12:58 UTC, merged