set distributable to false for log4j vulnerable java libs
ursgal/ursgal pull request #213
Opened 2022-03-09 13:42 UTC by MKoesters

2022-03-09 16:34 UTC, StSchulze requested changes
All checks are failing?

2022-03-09 16:50 UTC, MKoesters commented
upstream error in chemical-composition
I deployed a new version, but I did not introduce the changes for the new version, so I dont' know right now whats causing this

2022-03-09 16:54 UTC, MKoesters commented
maybe because of the new pyqms version, I'll try to find out

2022-03-18 14:00 UTC, StSchulze approved these changes

2022-04-29 12:10 UTC, merged